# run docker - docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

# confirm that docker is running - docker ps

# stop docker - docker stop mongo

# run docker compose - docker-compose up [-d]

version: '3.8'

services:
  mongo: 
    image: mongo
    container_name: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: